### ISSUE TITLE
Most data annotation attributes won't get their correct error messages

### ISSUE THREAD

**Issue by belangervince** [ForEvolve/ForEvolve.AspNetCore.Localization#21]
**Describe the bug**
From what I have tested, only the MaxLengthAttribute gets its correct translation.

**To Reproduce**
1. Force French localization.
2. Create a model with PhoneAttribute, EmailAttribute or CreditCardAttribute.
3. Create a view for that model.
4. Post a form that will fail.

**Expected behavior**
Should be getting messages in French.

**Screenshots**
![Annotation 2019-03-29 171143](https://user-images.githubusercontent.com/44981444/55262898-c4d49d00-5245-11e9-9c7b-c13e79a4db9e.jpg)

My app is using .NET Core 2.2 and I am using version 1.3.1 of ForEvolveAspNetCore.Localization

**Comment by Carl-Hugo** [comment]
Thanks, I will look into it

**Comment by Carl-Hugo** [comment]
Deploying the fixed version as `2.0.0` due to the following possible (most likely) breaking change:

- User-specified `ErrorMessage` on `DataTypeAttribute` might get overridden by `ForEvolve.AspNetCore.Localization`.

**Comment by belangervince** [comment]
Thanks for your work and very quick responses!

**Comment by Carl-Hugo** [comment]
You are welcome. 

As a bonus, it gave me the opportunity to clear some old issues like testing the messages to catch those errors before they break the library again. 

Moreover, it was raining and snowing outside 😉
