### ISSUE TITLE
Some validation messages stopped working

### ISSUE THREAD

**Issue by belangervince** [ForEvolve/ForEvolve.AspNetCore.Localization#25]
Hello,

I seem to be getting the correct error messages (in French), except for "IsRequired" which gives me the default english message.

**Comment by Carl-Hugo** [comment]
With what version of `.Net Core`?

**Comment by belangervince** [comment]
2.2

**Comment by Carl-Hugo** [comment]
When I run my sample project, with uri `https://localhost:5001/?culture=fr`, it seems to work.

![image](https://user-images.githubusercontent.com/5885505/58139599-6f938700-7c09-11e9-9f00-ff5a203c12ae.png)

Do you have a repro project?

**Comment by belangervince** [comment]
Je te reviens demain. Je vais essayer de reproduire mon cas. Merci!

**Comment by belangervince** [comment]
Localement, je travaille sur Windows Anglais avec VS Anglais. Tout fonctionne correctement (messages d'erreur en français). Dès que je publie sur un serveur AWS, les messages d'erreur redeviennent en anglais.

**Comment by Carl-Hugo** [comment]
Will be fun to diagnose I guess.

What are the AWS server's specs?
Have you tried different server configurations?
Have you tried other cloud providers? I'm wondering if that behavior is generalized or not.
Runs in a container or not?

Is it possible to automate AWS deployments (like you give me the automation script and repro project, and I can deploy it, try it out and try to identify the bug when I have a few minutes)?

**Comment by belangervince** [comment]
We didn't try another cloud provider or IIS on premise. It runs on an EC2 instance with Elastic Beanstalk. Unfortunately, there's not much else I can provide or disclose. I'll investigate further and keep you updated when I find out what's wrong. Thank you for your time once again.

**Comment by Carl-Hugo** [comment]
Ok, if I find a few minutes, I'll try to run the sample app *on an EC2 instance with Elastic Beanstalk*. If you find anything, please let me know.

**Comment by Carl-Hugo** [comment]
Ok, I was full of good intentions, but I had no time to dig into AWS infrastructure to deploy the sample project there. I will close this issue until you can provide me with a repro project, or confirm that the sample project does not work on AWS and provide me some instructions (or a script) about how to deploy that test project on AWS.
