### ISSUE TITLE
Upgrade projects to Core 3.1

### ISSUE THREAD

**Issue by philippedurocher** [ForEvolve/ForEvolve.AspNetCore.Localization#28]
**Is your feature request related to a problem? Please describe.**
Using Core 2.1 project with a 3.1 project triggers the following warning 
`Warning	AD0001	Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.`

I tried to install FxCop analyzers and Microsoft Analyzers nugets, but seems it's kind of a normal behavior that Microsoft won't fix. It happens when 2.x and 3.x are used in same project.

**Describe the solution you'd like**
Upgrade every projects in solution to Core 3.1 and republish a newer Nuget version for Core 3.1

**Describe alternatives you've considered**
I tried to upgrade the projects myself but could not transform the tests - ModelAttributes is deprecated in 3.1 and could not find a workaround or a rewrite strategy.

**Additional context**
No more request that this on. Your project is really great! I'm using it in french for validation errors and also for models resources in /Resources. Thank you!

**Comment by philippedurocher** [comment]
I realized ForEvolve Localization nuget was not the cause of my problem. Something else was triggering compilation warning in my projects. I cleared Nuget's cache, unloaded/reloaded the projects, rebuild and the warning was gone. Happy ending. Thanks again.

**Comment by Carl-Hugo** [comment]
Glad you found your problem!
