### ISSUE TITLE
Create a strategy that is using MVC routes to set language

### ISSUE THREAD

**Issue by Carl-Hugo** [ForEvolve/ForEvolve.AspNetCore.Localization#8]
It should be easy to create an application with URL looking like: `/en-US/whatever/else/here` that gets localized automatically.

The strategy should be enabled by default and should be easy to `opt-out`.

---

First, take a look at the existing providers: [Globalization and localization in ASP.NET Core | Implement a strategy to select the language/culture for each request](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization#implement-a-strategy-to-select-the-languageculture-for-each-request) and their implementations.

---

See also [RouteDataRequestCultureProvider.cs](https://github.com/aspnet/Localization/blob/3a29c26c46f9614210c93a14de902e9238b01e92/src/Microsoft.AspNetCore.Localization.Routing/RouteDataRequestCultureProvider.cs) to see if that could do the trick (maybe with this and adding a route).

**Comment by os1r1s110** [comment]
I guess you have already seen it, but if you are looking for a way to perform exactly what you described, see the excellent series of posts from Andrew Lock
[https://andrewlock.net/url-culture-provider-using-middleware-as-mvc-filter-in-asp-net-core-1-1-0/](url)

**Comment by Carl-Hugo** [comment]
Sorry for the delay @os1r1s110 I missed your comment. 

That said, I cannot say that I had seen that article and I will take a look at it before designing this part of the system. Thanks for sharing.

**Comment by Carl-Hugo** [comment]
Closing: no bandwidth + out of scope of this project
